version: 2

sources:
  - name: bronze
    description: "Fontes de dados raw ingeridas na camada Bronze."
    tables:
      - name: municipios_pe_geo
        description: "Tabela base com informações dos municípios de Pernambuco."
      - name: monitoramento_pluviometrico
        description: "Tabela raw de monitoramento pluviométrico da APAC."
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - codigo_posto
                - data
        columns:
          - name: codigo_posto
            tests:
              - not_null
          - name: data
            tests:
              - not_null
          - name: mesorregiao_id
            tests:
              - accepted_values:
                  values: [2601, 2602, 2603, 2604, 2605]
